[package]
name = "rust_os"
version = "0.1.0"
authors = ["MichalObi <ndwz123@gmail.com>"]

# need bootloader to initializes CPU and load our rust_os kernel

[dependencies]
bootloader_precompiled = "0.2.0"
