[package]
name = "rust_os"
version = "0.1.0"
authors = ["MichalObi <ndwz123@gmail.com>"]

# When we writing bare-metal binary we need to to change default panic behavior.
# Instead of stack unwinding (cleaning stack with OS help), we abort on panic.
